[project]
name = "fastmcpv2-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.11.3",
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
]
